apiVersion: apps/v1
kind: Daemonset
metadata:
  name: my-daemonset
  namespace: sunil
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    
    spec:
      containers:
      - name: jenkins
        image: vinodvanama/projecttrain
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: daemonset-service
  namespace: sunil
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80