
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  namespace: httpd
  labels:
    app: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd  # This should match the label in the template
  template:
    metadata:
      name: httpd
      labels:
        app: httpd  # Label in the template that should match the selector
    spec:
      containers:
        - name: cont1
          image: httpd
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpdservice
spec:
  type: LoadBalancer
  selector:
    app: httpd  # This should match the label in the Deployment selector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
