apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  namespace: httpd
  labels:
    app: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      name: httpd
    spec:
      containers:
        - name: cont1
          image: httpd
          ports:                # Correct indentation here
            - containerPort: 80  # Indent further for the specific port
---
apiVersion: v1
kind: Service
metadata:
  name: httpdservice
spec:
  type: LoadBalancer
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

