---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: sunil
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    
    spec:
      containers:
      - name: jenkins
        image: mysql:latest
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: sunil
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3306
    # Use 'LoadBalancer' for external access (if supported by your cluster)
