apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: swiggy1
  name: swiggy-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
      - name: cont1
        image: rahamshaik/trainservice:latest
        ports:
          - containerPort: 80
        # nodeSelector should be defined at the pod level
        nodeSelector:
          app: node1  # Label key and value for node selection
---
apiVersion: v1
kind: Service
metadata:
  name: abc
spec:
  type: LoadBalancer
  selector:
    app: swiggy1
  ports:
    - port: 80
      targetPort: 80
