apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: swiggy1
  name: swiggy-deploy
  namespace: srikanth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      nodeSelector: 
        app: node2
      containers:
        - name: cont1
          image: rahamshaik/trainservice:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: swiggy
  namespace: srikanth # Namespace for the Service
spec:
  type: LoadBalancer
  selector:
    app: swiggy1
  ports:
    - port: 80
      targetPort: 80
