apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: swiggy1
  name: swiggy-deploy
  namespace: roboshop  # Namespace for the Deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      nodeSelector:
        app: node1
      containers:
      - name: cont1
        image: rahamshaik/trainservice:latest
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: abc1
  namespace: roboshop  # Namespace for the Service
spec:
  type: LoadBalancer
  selector:
    app: swiggy1
  ports:
    - port: 80
      targetPort: 80
