apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: raham
  name: raham
  namespace: raham
spec:
  replicas: 3
  selector:
    matchLabels:
      app: raham
  template:
    metadata:
      labels:
        app: raham
    spec:
      containers:
      - name: cont1
        image: rahamshaik/rechargepaytm
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: raham
spec:
  type: LoadBalancer
  selector:
    app: raham
  ports:
    - port: 80
      targetPort: 80
