apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunil
  namespace: sunil
spec:
replicas: 3
  selector:
    matchLabels:
      app: sunil
      namespace: sunil
  template:
    metadata:
      labels:
        app: sunil
        namespace: sunil
    spec:
      containers:
      - name: sunil
      namespace: sunil
        image: sunilbokka12/sunil12-b
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sunil
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: sunil
spec:
  type: LoadBalancer
  selector:
    app: sunil
  ports:
  - port: 80
    targetPort: 80