---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunil
  namespace: sunil
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sunil
      namespace: sunil
  template:
    metadata:
      labels:
        app: sunil
        namespace: sunil
    spec:
      containers:
        - name: sunil
          image: jenkins/jenkins
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sunil
  namespace: sunil
spec:
  type: LoadBalancer
  selector:
    app: sunil
  ports:
    - port: 80
      targetPort: 8080
