---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunil
  namespace: sunil
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sunil
      namespace: sunil
  template:
    metadata:
      labels:
        app: sunil
        namespace: sunil
    spec:
      containers:
        - name: sunil
          image: rahamshaik/moviesservice
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sunil
spec:
  type: LoadBalancer
  selector:
    app: sunil
  ports:
    - port: 80
      targetPort: 80
