
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunil
  namespace: amulu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sunil
      namespace: sunil
  template:
    metadata:
      labels:
        app: sunil
        namespace: sunil
    spec:
      containers:
        - name: sunil
          image:  techworldwithsiva/app2
          ports:
            - containerPort: 80